const translations = {
    "uk": {
        "nav_project": "Проєкт",
        "nav_quality": "Якість",
        "nav_tech": "Технології",
        "nav_contacts": "Контакти",
        "hero_title": "ПОПП «Еліта»",
        "hero_subtitle": "Новий еталон інтенсивного садівництва.",
        "hero_text": "Ми об’єднали багатовіковий досвід італійських селекціонерів із потенціалом українського чорнозему. Наш сад у Тетієві — це втілення майбутнього агропромисловості, де кожен гектар працює за найвищими світовими стандартами.",
        "hero_btn": "Ознайомитися з проєктом",
        "proj_title": "Масштаб, що вражає. Технології, що надихають.",
        "proj_p1": "Проєкт промислового вирощування фундука ми розпочали у 2018 році. Сьогодні площа насаджень становить понад <strong>500 гектарів</strong> на околицях м. Тетіїв (ТОВ \"ПОПП ЕЛІТА\").",
        "proj_p2": "Фундук — це окультурена форма ліщини, рідної для українських лісів, але наш підхід перетворив його на високотехнологічний та високоефективний бізнес.",
        "proj_p3": "Наш сад створений за суворими італійськими стандартами. Ми інтегрували в нього передові світові рішення: від автоматизованого моніторингу стану дерева до інтелектуальних систем живлення. Сьогодні це не просто сільськогосподарське підприємство, а екосистема, яка буде актуальною десятиліттями.",
        "loc_title": "Локація",
        "loc_desc": "м. Тетіїв, Київська область.",
        "stat_title": "Статус",
        "stat_desc": "Один із найбільших інтенсивних садів України.",
        "inno_title": "Інновації",
        "inno_desc": "Впровадження систем точного землеробства з першого дня закладання.",
        "gen_title": "Фундук преміальної якості.",
        "gen_sub": "Основа нашого успіху — безкомпромісний вибір сортів. Ми вирощуємо легендарні італійські сорти, що цінуються найкращими кондитерами світу за їхній смак, аромат та калібр.",
        "v1_title": "1. Tonda Gentile",
        "v1_desc": "Цей сорт вважається найкращим у світі для кондитерської промисловості завдяки своїм неперевершеним органолептичним властивостям.",
        "origin_lbl": "Походження: ",
        "fruit_lbl": "Характеристики плоду: ",
        "kernel_lbl": "Ядро: ",
        "taste_lbl": "Смаковий профіль: ",
        "v1_origin": "Регіон П’ємонт, Північна Італія.",
        "v1_fruit": "Горіх середнього розміру, має виражену трилопатеву (тригранну) форму. Шкаралупа тонка, але міцна.",
        "v1_kernel": "Сферичне, з дуже високим виходом чистого ядра (46–48%). Легко бланшується (очищується від плівки) після обсмажування.",
        "v1_taste": "Має інтенсивний, стійкий аромат та солодкий посмак. Вважається еталоном для виробництва преміального шоколаду та джандуї.",
        "v2_title": "2. Tonda di Giffoni",
        "v2_desc": "Сорт, що є візитною карткою регіону Кампанія. Він цінується за ідеальну калібровку та універсальність.",
        "v2_origin": "Провінція Салерно, Італія.",
        "v2_fruit": "Горіх великого або середнього розміру, майже ідеально круглої форми.",
        "v2_kernel": "Біле, хрустке, з відмінною текстурою. Вихід ядра становить 44–47%.",
        "v2_taste": "Дуже ароматний сорт, який розкривається під час термічної обробки. Його форма робить його ідеальним для використання в цілому вигляді всередині цукерок та батончиків.",
        "export_txt": "Завдяки професійному догляду, навіть у складні кліматичні сезони ми отримуємо продукцію, якість якої порівнянна з кращими зразками чилійського фундука. Весь врожай контрактується на експорт.",
        "eco_title": "Екологічність та Технології",
        "eco_sub": "Сучасний підхід до вирощування, що зберігає довкілля та гарантує стабільну якість.",
        "b1_title": "Екологічна чистота",
        "b1_desc": "Зведене до мінімуму пестицидне навантаження зберігає чистоту ґрунтів і довкілля.",
        "b2_title": "Оптимізація ресурсів",
        "b2_desc": "Потребує мінімум ручної праці. 100 га саду обслуговують лише 5-7 кваліфікованих спеціалістів.",
        "b3_title": "«Зелене» зберігання",
        "b3_desc": "Зберігання горіха не потребує енергозатратних величезних холодильників з активним охолодженням.",
        "gold_title": "Золото для здоров'я",
        "gold_p1": "Фундук — це культура, яка має тисячолітню історію і завжди цінувалася за смак та унікальний склад. Його плоди по праву вважаються \"золотом\" завдяки високій поживній цінності.",
        "gold_p2": "Це продукт свідомого споживання, який ідеально вписується у рамки правильного харчування. Він формує ставлення до їжі як до цінності, а не як до порожніх калорій.",
        "futu_title": "Внесок у майбутнє",
        "futu_p1": "Багаторічні насадження сприяють збереженню екосистеми регіону. Один фундуковий сад може повноцінно плодоносити 50 років, а попит на поживні горіхи в світі стабільно зростає.",
        "futu_p2": "Наші горіхи проходять шлях від садів Київщини до полиць магазинів по всьому світу. Ми створюємо технологічне майбутнє сільського господарства України.",
        "foot_logo": "ПОПП «ЕЛІТА»",
        "foot_desc": "Приватне орендне племінне підприємство «Еліта».",
        "foot_chief": "Завжди на зв'язку. Директор — Мостова Леся Анатоліївна.",
        "foot_ct_title": "Контакти",
        "foot_addr": "Україна, Київська обл., м. Тетіїв.",
        "foot_copy": "&copy; 2026 ПОПП «Еліта». Усі права захищені."
    },
    "en": {
        "nav_project": "Project",
        "nav_quality": "Quality",
        "nav_tech": "Technologies",
        "nav_contacts": "Contacts",
        "hero_title": "PAEP \"Elita\"",
        "hero_subtitle": "A new standard in intensive horticulture.",
        "hero_text": "We combined centuries of Italian breeding experience with the potential cycle of Ukrainian black soil. Our orchard in Tetiiv is the embodiment of the agricultural future: every hectare operates at the highest global standards.",
        "hero_btn": "Explore the Project",
        "proj_title": "Impressive scale. Inspiring technologies.",
        "proj_p1": "We launched our industrial hazelnut cultivation project in 2018. Today, our orchard spans over <strong>500 hectares</strong> near the town of Tetiiv (LLC \"PAEP Elita\").",
        "proj_p2": "Hazelnut is a cultured form of hazel, native to Ukrainian forests, but our approach has transformed it into a highly technological and efficient business.",
        "proj_p3": "Our orchard was established according to strict Italian standards. We integrated cutting-edge global solutions: from automated tree health monitoring to intelligent nutrition systems. Today, this is not just an agricultural enterprise, but an ecosystem that will remain relevant for decades.",
        "loc_title": "Location",
        "loc_desc": "Tetiiv, Kyiv region, Ukraine.",
        "stat_title": "Status",
        "stat_desc": "One of the largest intensive orchards in Ukraine.",
        "inno_title": "Innovations",
        "inno_desc": "Implementation of precision farming systems from day one.",
        "gen_title": "Premium Quality Hazelnut.",
        "gen_sub": "The foundation of our success is the uncompromising selection of varieties. We grow legendary Italian cultivars prized by the world's best confectioners for their flavor, aroma, and caliber.",
        "v1_title": "1. Tonda Gentile",
        "v1_desc": "This variety is globally considered the best for the confectionery industry due to its unsurpassed organoleptic properties.",
        "origin_lbl": "Origin: ",
        "fruit_lbl": "Fruit features: ",
        "kernel_lbl": "Kernel: ",
        "taste_lbl": "Flavor profile: ",
        "v1_origin": "Piedmont region, Northern Italy.",
        "v1_fruit": "Medium-sized nut with a pronounced trilobate (three-sided) shape. The shell is thin but strong.",
        "v1_kernel": "Spherical, with a very high clean kernel yield (46–48%). Easily blanched (peeled) after roasting.",
        "v1_taste": "Has an intense, persistent aroma and sweet aftertaste. Considered the benchmark for premium chocolate and gianduja production.",
        "v2_title": "2. Tonda di Giffoni",
        "v2_desc": "The signature variety of the Campania region. Highly prized for its perfect calibration and versatility.",
        "v2_origin": "Province of Salerno, Italy.",
        "v2_fruit": "Large or medium-sized nut, almost perfectly round shape.",
        "v2_kernel": "White, crisp, with excellent texture. Kernel yield is 44–47%.",
        "v2_taste": "Very aromatic variety that fully reveals itself during thermal processing. Its shape makes it ideal for whole use inside candies and candy bars.",
        "export_txt": "Thanks to professional care, even in difficult climatic seasons we obtain products whose quality is comparable to the best samples of Chilean hazelnut. The entire harvest is contracted for export.",
        "eco_title": "Ecology and Technologies",
        "eco_sub": "A modern approach to farming that preserves the environment and guarantees stable quality.",
        "b1_title": "Ecological purity",
        "b1_desc": "Minimized pesticide load preserves the purity of soils and the environment.",
        "b2_title": "Resource optimization",
        "b2_desc": "Requires minimal manual labor. 100 ha of orchard are serviced by only 5-7 qualified specialists.",
        "b3_title": "«Green» storage",
        "b3_desc": "Nut storage does not require energy-consuming massive refrigerators with active cooling.",
        "gold_title": "Gold for Health",
        "gold_p1": "Hazelnut is a crop with a thousand-year history, always valued for its taste and unique composition. Its fruits are rightfully considered \"gold\" due to high nutritional value.",
        "gold_p2": "It is a product of conscious consumption that perfectly fits into the framework of healthy eating. It forms an attitude towards food as a value, rather than empty calories.",
        "futu_title": "Contribution to the Future",
        "futu_p1": "Perennial plantings contribute to the preservation of the region's ecosystem. A single hazelnut orchard can fully bear fruit for 50 years, and the global demand for nutritious nuts is steadily growing.",
        "futu_p2": "Our nuts travel from the orchards of the Kyiv region to store shelves all over the world. We are creating the technological future of Ukraine's agriculture.",
        "foot_logo": "PAEP \"ELITA\"",
        "foot_desc": "Private Agricultural Enterprise of Partners \"Elita\".",
        "foot_chief": "Always in touch. Director — Lesia Mostova.",
        "foot_ct_title": "Contacts",
        "foot_addr": "Ukraine, Kyiv region, Tetiiv.",
        "foot_copy": "&copy; 2026 PAEP \"Elita\". All rights reserved."
    },
    "it": {
        "nav_project": "Progetto",
        "nav_quality": "Qualità",
        "nav_tech": "Tecnologia",
        "nav_contacts": "Contatti",
        "hero_title": "PAEP \"Elita\"",
        "hero_subtitle": "Un nuovo standard nell'orticoltura intensiva.",
        "hero_text": "Abbiamo combinato secoli di esperienza riproduttiva italiana con il potenziale del suolo nero ucraino. Il nostro noccioleto a Tetiiv è l'incarnazione del futuro agricolo, dove ogni ettaro opera ai massimi standard mondiali.",
        "hero_btn": "Scopri il Progetto",
        "proj_title": "Scala impressionante. Tecnologie stimolanti.",
        "proj_p1": "Abbiamo avviato il nostro progetto di coltivazione industriale di nocciole nel 2018. Oggi le nostre piantagioni coprono oltre <strong>500 ettari</strong> vicino alla città di Tetiiv (SRL \"PAEP Elita\").",
        "proj_p2": "Il nocciolo è una forma coltivata della pianta nativa delle foreste ucraine, ma il nostro approccio l'ha trasformato in un'impresa altamente tecnologica ed efficiente.",
        "proj_p3": "Il nostro noccioleto è stato creato secondo rigorosi standard italiani. Abbiamo integrato le migliori soluzioni mondiali: dal monitoraggio automatizzato dello stato degli alberi ai sistemi di nutrizione intelligenti. Oggi questa non è solo un'impresa agricola, ma un ecosistema che rimarrà rilevante per decenni.",
        "loc_title": "Posizione",
        "loc_desc": "Tetiiv, regione di Kiev, Ucraina.",
        "stat_title": "Stato",
        "stat_desc": "Uno dei più grandi noccioleti intensivi in Ucraina.",
        "inno_title": "Innovazioni",
        "inno_desc": "Implementazione di sistemi di agricoltura di precisione dal primo giorno.",
        "gen_title": "Nocciole di Qualità Premium.",
        "gen_sub": "La base del nostro successo è la rigorosa selezione delle varietà. Coltiviamo letgendarie varietà italiane apprezzate dai migliori pasticceri del mondo per sapore, aroma e calibro.",
        "v1_title": "1. Tonda Gentile",
        "v1_desc": "Questa varietà è considerata a livello globale la migliore per l'industria dolciaria grazie alle sue insuperabili proprietà organolettiche.",
        "origin_lbl": "Origine: ",
        "fruit_lbl": "Caratteristiche del frutto: ",
        "kernel_lbl": "Nocciolo: ",
        "taste_lbl": "Profilo aromatico: ",
        "v1_origin": "Regione Piemonte, Nord Italia.",
        "v1_fruit": "Nocciola di media grandezza, ha una marcata forma trilobata. Il guscio è sottile ma resistente.",
        "v1_kernel": "Sferico, con una resa in granella pulita molto elevata (46–48%). Facilmente pelabile dopo la tostatura.",
        "v1_taste": "Ha un aroma intenso, persistente e retrogusto dolce. Considerato il punto di riferimento per la produzione di cioccolato premium e gianduia.",
        "v2_title": "2. Tonda di Giffoni",
        "v2_desc": "La varietà sinonimo della regione Campania. Molto apprezzata per la perfetta calibrazione e versatilità.",
        "v2_origin": "Provincia di Salerno, Italia.",
        "v2_fruit": "Nocciola di calibro grande o medio, forma quasi perfettamente tonda.",
        "v2_kernel": "Bianco, croccante, con ottima consistenza. La resa alla sgusciatura è del 44-47%.",
        "v2_taste": "Varietà molto aromatica che si esprime al meglio durante i trattamenti termici. La forma la rende ideale per utilizzo intero in cioccolatini e snack.",
        "export_txt": "Grazie alla cura professionale, anche in stagioni climatiche difficili otteniamo prodotti la cui qualità è paragonabile ai migliori campioni di nocciole cilene. L'intero raccolto è destinato all'esportazione.",
        "eco_title": "Ecologia e Tecnologie",
        "eco_sub": "Un approccio moderno all'agricoltura che preserva l'ambiente e garantisce una qualità stabile.",
        "b1_title": "Purezza ecologica",
        "b1_desc": "Il carico di pesticidi ridotto al minimo preserva la purezza dei suoli e dell'ambiente.",
        "b2_title": "Ottimizzazione delle risorse",
        "b2_desc": "Richiede un lavoro manuale minimo. 100 ettari di frutteto sono serviti da soli 5-7 specialisti qualificati.",
        "b3_title": "Stoccaggio \"Verde\"",
        "b3_desc": "Lo stoccaggio delle noci non richiede massicci frigoriferi a forte consumo di energia con raffreddamento attivo.",
        "gold_title": "Oro per la Salute",
        "gold_p1": "La nocciola è una coltura con una storia millenaria e da sempre apprezzata per il suo gusto e composizione unica. I suoi frutti sono considerati \"oro\" per il loro elevato valore nutrizionale.",
        "gold_p2": "È un prodotto di consumo consapevole che si inserisce perfettamente nel quadro di una sana alimentazione. Forma un atteggiamento verso il cibo come valore, non come calorie vuote.",
        "futu_title": "Contributo al Futuro",
        "futu_p1": "Le piantagioni perenni contribuiscono alla conservazione dell'ecosistema della regione. Un noccioleto può produrre frutti per 50 anni e la domanda mondiale è in costante aumento.",
        "futu_p2": "Le nostre noci viaggiano dai frutteti della regione di Kiev agli scaffali dei negozi di tutto il mondo. Stiamo creando il futuro tecnologico dell'agricoltura ucraina.",
        "foot_logo": "PAEP \"ELITA\"",
        "foot_desc": "Azienda Agricola Privata di Partner \"Elita\".",
        "foot_chief": "Sempre in contatto. Direttore — Lesia Mostova.",
        "foot_ct_title": "Contatti",
        "foot_addr": "Ucraina, regione di Kiev, Tetiiv.",
        "foot_copy": "&copy; 2026 PAEP \"Elita\". Tutti i diritti riservati."
    }
};

function setLang(lang) {
    document.querySelectorAll('[data-i18n]').forEach(el => {
        const key = el.getAttribute('data-i18n');
        if (translations[lang] && translations[lang][key]) {
            el.innerHTML = translations[lang][key]; // Using innerHTML to preserve <strong> tags
        }
    });

    // Update active button state
    document.querySelectorAll('.lang-btn').forEach(btn => {
        btn.classList.remove('active');
    });
    const activeBtn = document.querySelector(`.lang-btn[data-lang="${lang}"]`);
    if(activeBtn) {
        activeBtn.classList.add('active');
    }
    
    // Set document lang attribute
    document.documentElement.lang = lang;
}
